name: python_workshop_blockchain_week01
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h716150d_1
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - bip-utils==2.10.0
      - bitcoinlib==0.7.6
      - cbor2==5.8.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - coincurve==21.0.0
      - crcmod==1.7
      - ecdsa==0.19.1
      - ed25519-blake2b==1.4.1
      - greenlet==3.3.0
      - idna==3.11
      - mnemonic==0.21
      - numpy==1.26.4
      - py-sr25519-bindings==0.2.3
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pynacl==1.6.2
      - requests==2.32.5
      - six==1.17.0
      - sqlalchemy==2.0.45
      - typing-extensions==4.15.0
      - urllib3==2.6.3
prefix: C:\Users\Asus\anaconda3\envs\python_workshop_blockchain_week01
